await page.fill("input#user-name", "standard_user")
await page.fill("input#password", "secret_sauce")
await page.click("input#login-button")
await page.wait_for_url("/inventory.html")
await page.click("#add-to-cart-sauce-labs-backpack")
await page.locator("span.shopping_cart_badge").wait_for(state="visible")
await page.click("a.shopping_cart_link")
await page.click("button#checkout")
await page.fill("input#first-name", "John")
await page.fill("input#last-name", "Doe")
await page.fill("input#postal-code", "12345")
await page.click("input#continue")
await page.click("button#finish")
await page.wait_for_url("/checkout-complete.html")